// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnnzbmlnfddkwtlbawxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBubnpibWxuZmRka3d0bGJhd3huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzY4MDgsImV4cCI6MjA2NTU1MjgwOH0.qxF0G8CFLWG0NtjUyXzIDikGsvAXlSGxReamYTgkf0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);